---
kind: Namespace
apiVersion: v1
metadata:
  name: polkadot-polkassembly
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gitlab
  namespace: polkadot-polkassembly
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab
  namespace: polkadot-polkassembly
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: polkadot-polkassembly
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: polkadot-polkassembly
  namespace: polkadot-polkassembly
spec:
  domains:
    - polkadot.polkassembly.network
    - polkadot.polkassembly.io
